# Generated by Django 5.2.1 on 2026-05-17 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('name', models.CharField(max_length=180, unique=True, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'proyecto',
                'verbose_name_plural': 'proyectos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Cruce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('codigo_j', models.CharField(blank=True, max_length=40, verbose_name='código J')),
                ('interseccion', models.CharField(max_length=240, verbose_name='intersección')),
                ('comuna', models.CharField(blank=True, max_length=120, verbose_name='comuna')),
                ('fecha_terreno', models.DateField(blank=True, null=True, verbose_name='fecha de terreno')),
                ('evaluador', models.CharField(blank=True, max_length=120, verbose_name='evaluador')),
                ('jornada', models.CharField(blank=True, choices=[('PM', 'Punta mañana'), ('PT', 'Punta tarde'), ('PMD', 'Mediodía'), ('FP', 'Fuera de punta')], max_length=10, verbose_name='jornada')),
                ('horario_inicio', models.TimeField(blank=True, null=True, verbose_name='horario inicio')),
                ('horario_fin', models.TimeField(blank=True, null=True, verbose_name='horario fin')),
                ('solicita', models.CharField(blank=True, max_length=180, verbose_name='solicita')),
                ('estado_semaforo', models.CharField(blank=True, choices=[('En Sistema', 'En Sistema'), ('Aislado', 'Aislado')], max_length=40, verbose_name='estado semáforo')),
                ('estado', models.CharField(blank=True, choices=[('Realizado', 'Realizado'), ('Programado', 'Programado'), ('Evento Extraprogramático', 'Evento Extraprogramático'), ('Por confirmar', 'Por confirmar')], max_length=80, verbose_name='estado')),
                ('realizo_modificacion', models.BooleanField(default=False, verbose_name='se realizó modificación')),
                ('modificacion_texto', models.TextField(blank=True, verbose_name='modificación')),
                ('problema', models.TextField(blank=True, verbose_name='problema/motivo')),
                ('observaciones', models.TextField(blank=True, verbose_name='observaciones')),
                ('rutas_texto', models.TextField(blank=True, verbose_name='rutas asociadas')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cruces', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_cruces', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cruces', to='cruces.project', verbose_name='proyecto/obra')),
            ],
            options={
                'verbose_name': 'cruce',
                'verbose_name_plural': 'cruces',
                'ordering': ['-fecha_terreno', 'interseccion'],
            },
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/', verbose_name='archivo')),
                ('original_name', models.CharField(max_length=255, verbose_name='nombre original')),
                ('file_type', models.CharField(choices=[('bitacora', 'Bitácora'), ('rutas_antes', 'Rutas antes'), ('rutas_despues', 'Rutas después'), ('reporte', 'Reporte'), ('otro', 'Otro')], default='otro', max_length=30, verbose_name='tipo')),
                ('cruce', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='cruces.cruce')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'archivo',
                'verbose_name_plural': 'archivos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('name', models.CharField(max_length=180, verbose_name='nombre')),
                ('horario_inicio', models.TimeField(blank=True, null=True, verbose_name='horario inicio')),
                ('horario_fin', models.TimeField(blank=True, null=True, verbose_name='horario fin')),
                ('result', models.CharField(choices=[('mejoro', 'Mejoró'), ('empeoro', 'Empeoró'), ('sin_cambio', 'Sin cambio'), ('sin_datos', 'Sin datos')], default='sin_datos', max_length=20, verbose_name='resultado')),
                ('summary', models.JSONField(blank=True, default=dict, verbose_name='resumen')),
                ('route_rows', models.JSONField(blank=True, default=list, verbose_name='detalle rutas')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cruce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='cruces.cruce')),
                ('file_after', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses_after', to='cruces.uploadedfile')),
                ('file_before', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses_before', to='cruces.uploadedfile')),
            ],
            options={
                'verbose_name': 'análisis',
                'verbose_name_plural': 'análisis',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='cruce',
            constraint=models.UniqueConstraint(condition=models.Q(('codigo_j', ''), _negated=True), fields=('codigo_j',), name='unique_non_empty_codigo_j'),
        ),
    ]
