# Generated by Django 5.2.1 on 2026-05-18 00:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='token')),
                ('title', models.CharField(blank=True, max_length=180, verbose_name='título')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expira')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_reports', to='cruces.analysis')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'reporte compartido',
                'verbose_name_plural': 'reportes compartidos',
                'ordering': ['-created_at'],
            },
        ),
    ]
