# Generated by Django 5.2.1 on 2026-05-18 01:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruces', '0002_sharedreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_analyses', to=settings.AUTH_USER_MODEL, verbose_name='compartido con'),
        ),
        migrations.AddField(
            model_name='cruce',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_cruces', to=settings.AUTH_USER_MODEL, verbose_name='compartido con'),
        ),
    ]
